apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "nginx.name" . }}
type: Opaque
data:
  password: {{ b64enc .Values.secret.password }}
  username: {{ b64enc .Values.secret.user }}
